Add types to `exports` field in package.json
codemirror/legacy-modes pull request #15
Opened 2023-09-12 12:54 UTC by blaumeise20

I could not manage to get this package working with `Node16` module resolution in TypeScript, because apparently it "can't find the corresponding type definitions for ...". This PR should fix those issues.

2023-09-12 13:16 UTC, marijnh commented
Did you verify that is made stuff resolve properly? (For example by editing the file in your node_modules.)

2023-11-14 07:12 UTC, blaumeise20 commented
Sorry I completely forgot this, I will check it later.

2025-03-13 13:34 UTC, stof commented on package.json
> -  "types": "dist/index.d.ts",
shouldn't this be lept if the `module` entry (on next line) is kept ?

2025-09-30 11:03 UTC, jbmichaels1984 requested changes
Android 16 beta free

2025-09-30 11:06 UTC, closed without merging